### ISSUE TITLE
the MAE loss does not seem to decrease in the cold start environment

### ISSUE THREAD

**Issue by panghaoyu** [hoyeoplee/MeLU#11]
hi，
I tested the model on the all_cold dataset after every epoch, but with the default parameters, the MAE loss did not seem to decrease:
![all_new_MAEloss](https://user-images.githubusercontent.com/45325074/100578701-c6f5d580-331d-11eb-87a8-9fa921094040.png)
and, I also do this in the old(warm start) dataset, the result is good:
![old_MAEloss](https://user-images.githubusercontent.com/45325074/100578753-df65f000-331d-11eb-8dbd-1a31b53b1681.png)
do you know why this happens?
thank you!

**Comment by Jie190916** [comment]
Hi, have you solved this problem?
