### ISSUE TITLE
How were the item/user state files created?

### ISSUE THREAD

**Issue by joshzwiebel** [hoyeoplee/MeLU#12]
How were the item_user_cold_state.json etc.. files created and what do they represent?

**Comment by roy-lei** [comment]
Hi, I'm also very curious about this question, do you figure it out?

**Comment by joshzwiebel** [comment]
Sorry I do not recall how they were created but I remember that they represent training files where the model has been exposed to either iitem data or user data. Warm and cold refer to whether it has seen that information. I would recommend checking the paper out for more specific information. Sorry I cant be of more help.

https://arxiv.org/pdf/1908.00413.pdf
